### ISSUE TITLE
cannot get rcloneosx to work

### ISSUE THREAD

**Issue by atanasj** [rsyncOSX/rcloneosx#152]
Hi, 

I have downloaded and compiled `rcloneosx` as per the `rsyncOSX` instructions. However, I cannot get `sync` jobs to work via the `rcloneosx` GUI. I have tested the same commands and arguments via the command line, and everything works. 

I received the following warnings in `Xcode` when compiling the app: `Variable 'self' was written to, but never read`. 

This error occurs twice: 
line 28 of `rcloneosx-master/RcloneOSX/Model/ScheduleOperation/Timer/ScheduleOperationTimer.swift`, and line 16 of `rcloneosx-master/RcloneOSX/Model/ScheduleOperation/Dispatch/ScheduleOperationDispatch.swift`. Not sure if this is causing it to not work properly.  

I'm on `macOS 10.13.3`. Please let me know if you need any more info. 

Thank you in advance for your help. 

Regards,
Atanas.

**Comment by rsyncOSX** [comment]
The "error" is just Xcode complaining about a weak self declaration, it is required to avoid memory leaks.. 

Have you tried to download and execute the compiled version? If that is working you should get your own compiled version to work? 

I will look into the code after work today to advise some breakpoints in code.

**Comment by atanasj** [comment]
Thanks for your reply. I should have checked the `releases` tab. I've downloaded the compiled version, and I'm still not able to `sync` with the remote. However, I have just tested `rsync` via the command line, and the only way I can get it to work is if I run it as `sudo`. 

Not sure what is happening. I'll post over on the `rsync` page, but would you have any ideas?

**Comment by rsyncOSX** [comment]
I think you might have found the issue. You may try to install rclone in a catalog in your home directory and make RcloneOSX aware of that version (add full path). There is no way for RcloneOSX to execute commands which require sudo to work. After installing rclone in in a catalog in your home directory try to get i work by copy and paste in a terminal window to see it work before using RcloneOSX..
![skjermbilde 2018-03-05 kl 12 04 56](https://user-images.githubusercontent.com/22427340/36971886-84c9eec8-206d-11e8-86ec-4b9319c70060.png)

**Comment by atanasj** [comment]
I didn't know there was a compiled version, that's much easier---thanks. I'm not sure how to move` rclone`. Is it via the` mv` command, or something different? I also need to use `sudo` to write to the`rclone.config` file too.... Mysterious?

**Comment by rsyncOSX** [comment]
I would just download another copy from https://github.com/ncw/rclone/releases and copy version 1.39 of rclone in a local catalog, dont move anything. Add the path for rclone in userconfig and rcloneosx will check for it. You will also see the version number in the right bottom view if rclone is found, if not there will be an error message..
The sudo might have something to do with file permissions on your rclone binary, dont know... Anyway, try to download...

**Comment by atanasj** [comment]
Update. This now works as expected. I had to `sudo chmod` then `rclone.conf` file, and we're all good. Thanks for your help. Just one more question please... can I `sync` to a github `repo`?

**Comment by atanasj** [comment]
Sorry, I meant `sudo chown -R`...

**Comment by rsyncOSX** [comment]
Glad it works for you now.. I dont know about rclone and GitHub? RcloneOSX and rclone is not my primary work. I did RcloneOSX based on the work of RsyncOSX. For me rsync is a more effective tool and most of my development is in RsyncOSX. I am updating parts of RcloneOSX now based on last version of RsyncOSX..
