### ISSUE TITLE
Detailed Progress

### ISSUE THREAD

**Issue by pvlvsk** [rsyncOSX/rcloneosx#208]
Hello,

thank you for developing this. Do you plan to implement a live detailed sync progress info instead of one progress bar? Perhaps it would be sufficient for the start if we would see rclone's console output somewhere during upload and not after that?

**Comment by rsyncOSX** [comment]
A solution is underway... as part of updating RcloneOSX a "live" update of output from rclone is available... a release candidate will be released soon...

<img width="1282" alt="skjermbilde 2018-08-10 kl 15 34 02" src="https://user-images.githubusercontent.com/22427340/43960812-791fb400-9cb3-11e8-8d8a-02359a2f4de7.png">

**Comment by rsyncOSX** [comment]
Will be released in version 1.5.5.
