### ISSUE TITLE
icon

### ISSUE THREAD

**Issue by Chamiu** [rsyncOSX/rcloneosx#40]
It is indistinguishable to arrange icons of RcloneOSX and RsyncOSX.
Since Rclone OSX has a different function from Rsync OSX, we think that it is better to explicitly make icons different.
To express clouds with red or blue blur.

Rclone OSXとRsyncOSXのiconを並べると見分けが付かない。Rclone OSXはRsync OSXとは異なる機能を持っているため、明示的にアイコンを異ならせる方が良いと考える。赤や青のぼかしで雲を表現するとか。

**Comment by rsyncOSX** [comment]
I do agree, I will make a new icon for RcloneOSX. If someone offer to assist me in adjusting the icon please do...

**Comment by rsyncOSX** [comment]
App image is updated 15 Nov 2017, new app icon.
