### ISSUE TITLE
Some texts (buttons) are black in dark mode

### ISSUE THREAD

**Issue by aahung** [rsyncOSX/rcloneosx#430]
As shown in the screenshot below, "Profile: default" label and top button rows are dark.

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/3804518/59307469-6e2b0c80-8c53-11e9-9866-5cbc9820ae83.png">

**Comment by rsyncOSX** [comment]
They are initially set to be dark in default profile. In "light mode" they are OK to read.. but I see the issue.. I will make a change in the next release...

**Comment by rsyncOSX** [comment]
Code is updated, default profile is color, other profiles are either black or white depended upon light or dark mode..

<img width="1204" alt="Skjermbilde 2019-06-12 kl  17 19 41" src="https://user-images.githubusercontent.com/22427340/59364221-cbe45500-8d36-11e9-9758-85257746403c.png">
<img width="1204" alt="Skjermbilde 2019-06-12 kl  17 21 12" src="https://user-images.githubusercontent.com/22427340/59364223-cf77dc00-8d36-11e9-8ceb-47a4a67155b2.png">

**Comment by aahung** [comment]
Thanks!
