### ISSUE TITLE
Is there a place to add your rclone.conf path?

### ISSUE THREAD

**Issue by bf4648** [rsyncOSX/rcloneosx#451]
Maybe I missed it but is there a place to load your rclone.conf path inside the GUI?

**Comment by rsyncOSX** [comment]
As fas as I can understand there is a flag --config to specify placement of rclone.conf. 
--config string                        Config file. (default "$HOME/.config/rclone/rclone.conf")

You might try this.. There is no global setting for it, you hav to add it to every configuration..

<img width="1204" alt="Skjermbilde 2019-07-27 kl  08 06 05" src="https://user-images.githubusercontent.com/22427340/61990682-accf2780-b045-11e9-8d6c-7e8259400722.png">
