### ISSUE TITLE
How to use encrypted rclone config?

### ISSUE THREAD

**Issue by ribtoks** [rsyncOSX/rcloneosx#545]
Hi @rsyncOSX 

Thanks for developing `rcloneosx`!

My rclone config is encrypted and it seems there's no way to use it with rcloneosx. Please correct me if I'm wrong.

**Comment by rsyncOSX** [comment]
Hi @ribtoks ..

That is a problem today? I might be a solution for it, dont know yet.. I have to look into it and see if there are any way for rcloneosx to safely open an encrypted config.. If you can sched some light into how would be nice as well ...

**Comment by ribtoks** [comment]
That's not a problem today, rather in general.

**Comment by rsyncOSX** [comment]
I have just read about encrypt the config file and there might be a possibility to use an environment variable RCLONE_CONFIG_PASS which are passed to the Swift object which kicks off the actual work... But, it is important that the actual password is not stored and it has to be entered every time using rcloneosx.. as for the command line rclone ...

**Comment by ribtoks** [comment]
Sounds good. Yes, it's important to keep the same behavior as command line tool (e.g. not to store password)

**Comment by rsyncOSX** [comment]
I will check it out in a few days.. kind of busy at work next couple of days.. The password needs to be entered when rcloneosx starts and ahead of reading the default profile. It will probably be a combination of setting read encrypted rclone config in rcloneosx userconfig. And if true rcloneosx halts and asks for password ahead of reading default config at startup.. should work.. 
will do some preliminary tests utilizing RCLONE_CONFIG_PASS=password and verify that it works..

**Comment by rsyncOSX** [comment]
I just did a short test, from command line it works.. In code I am passing environment variable to the process object as shown below: [String: String]. It works fine in RsyncOSX passing some SSH environment to rsync, but it fails in rcloneosx.. 
`task.environment = ["RCLONE_CONFIG_PASS": "Thomas123"]`
Adding this code causes rclone to produce some weird error.. this does not work..
The only way to enable this is to pass the password as a param when executing rclone.. rsync does not allow it, and I suspect rclone is not allowing it as well... 
So, for the moment I am stuck...

**Comment by ribtoks** [comment]
if it works from command line then it seems that somehow you're using it wrong from objective-c. Sorry, cannot help here since I'm not an expert.

**Comment by rsyncOSX** [comment]
The environment is used with success in RsyncOSX, and it is the only way to pass an environment variable to the Process object..
https://developer.apple.com/documentation/foundation/process/1409412-environment
It seems like there is no solution for it, I am sorry.. I am leaving the issue open, I will do some more googling about rclone and passing password as parameter.. but, no promises...
