### ISSUE TITLE
Instability and Lack of Documentation

### ISSUE THREAD

**Issue by cyberjew** [rsyncOSX/rcloneosx#548]
Hello - with all due respect, how does one even begin to use this GUI?

Going to the 'Help' menu brings up an incredibly useful message - "Help isn't available for rcloneosx"

IMHO - an application without documentation is only 50% complete.

I've been using rclone for quite some time now and, unless the installation of RcloneOSX using the DMG provided on GitHub is completely broken, there is only one place in the GUI where I can browse any resources already present in my rclone config file: Add -> Cloud Server Parameters -> Cloud Service

I can select the drop-down to the right of the dialog box and find my existing drives. That's about it. As soon as I go to the Files tab and try to search for any files on my remote drive, RcloneOSX crashes.

Process:               rcloneosx [7635]
Path:                  /Applications/RcloneOSX.app/Contents/MacOS/rcloneosx
Identifier:            no.blogspot.rcloneosx
Version:               2.0.6 (1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           rcloneosx [7635]
User ID:               501

Date/Time:             2020-02-16 01:51:08.954 -0500
OS Version:            Mac OS X 10.15.3 (19D76)
Report Version:        12
Anonymous UUID:        A441A4D1-D6D0-A10A-B8BF-3CABE2FA7EFB

Time Awake Since Boot: 11000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [7635]

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread

**Comment by rsyncOSX** [comment]
Hi.. I just reduced the size of the error log..  and thx for your comments and issue...

I do agree about documentation and there should be an updated user doc. When I commenced develop RcloneOSX (as a port of RsyncOSX) the plan was to port most of functions from RsyncOSX into RcloneOSX. I thought rclone and rsync was a kind of equal tools, but it is not and that makes further development of RcloneOSX difficult. In RsyncOSX I have combined the the views Files and Restore into one view. Doing the same for RcloneOSX is more difficult and I am missing the motivation for doing that. I am not using RcloneOSX myself on a regular basis myself. I have only three configs for my RcloneOSX, encrypt, dropbox and onenote. I am not experiencing any crash in Files or Restore.. 

I dont have time for developing docs for RcloneOSX, but I can fore sure check what causes the crash for you. But then I need to know which remote cloud the config is. There might be an issue about that remote cloud? 

The alternative is also to remove Files and Remote from RcloneOSX and just make it as a tool for synchronizing files, not restore..

**Comment by cyberjew** [comment]
I only have one cloud drive in my rclone.conf configuration file - it's a Google Drive folder. I am the owner of the Google Drive which is part of my GSuite for Business account. I am using a custom Oauth token and secret so the Google API usage is tracked against my account as opposed to the generic token that Rclone includes out of the box.

I've been using rclone from the CLI for purposes of syncing files shared with me to folders where I am the file owner so, if they decide to retract the shares, I still have copies. I've never run into any issues with rclone using it for this purpose. I was hoping to be able to use RcloneOSX to provide a nice GUI front-end fo 

Given the sensitivity of the tokens within, I cannot share the rclone.conf file, but if you have any specific questions, I can do my best to answer them.

**Comment by rsyncOSX** [comment]
I have only Onedrive and Dropbox setup (and a local encrypted). I will setup a Google Drive  connection tomorrow and test it.. I will let you know how it works.. And if there are any bugs I will fix them right away ...

**Comment by rsyncOSX** [comment]
Hi, I created a default google drive config, default values, and tested it with small data.. No errors, but it does not mean it can fail with more data. Does it fail for you at once or does it take some time?

<img width="1380" alt="Skjermbilde 2020-02-20 kl  07 59 44" src="https://user-images.githubusercontent.com/22427340/74909038-b2aca180-53b7-11ea-87a0-62347e9be8a5.png">
<img width="1204" alt="Skjermbilde 2020-02-20 kl  08 00 43" src="https://user-images.githubusercontent.com/22427340/74909033-ae808400-53b7-11ea-9f24-9eda225dab4f.png">
<img width="1365" alt="Skjermbilde 2020-02-20 kl  08 01 40" src="https://user-images.githubusercontent.com/22427340/74909020-a7f20c80-53b7-11ea-9af7-04898c11c7a1.png">

**Comment by cyberjew** [comment]
Thanks for offering to do that. If there's anything I can do to help you collect logs/debug information, I would be happy to do so. It would be great knowing that others using your application won't run into the same issue!

**Comment by cyberjew** [comment]
It fails for me instantly - every time I try to use it.

When you tested it, did you use the default OAuth identity that's included with rclone? Or did you enable the Google Drive APIs and generate an OAuth token on their developer portal?

I'm going to see if I can create a quick video to show you what's going on with my set up.

If there's anything I can collect from my side to help you debug this, I'd be happy to help you. Another option would be for us to get on a web meeting (I use Zoom at work). I can let you debug from my computer.  It would be great to know that this will work consistently for others as well.

**Comment by cyberjew** [comment]
One thing I'll add - my Google Drive has several TB of data. Since it's tied to my G Suite for Business account, they provide me with unlimited storage. I take advantage of the "unlimited" aspect. :-)

**Comment by rsyncOSX** [comment]
I just created a default config, using default options as rclone suggested.. I did not enable Google Drive API, I tried but got some troubles during that process..
Another option is for you to clone the repository and run RcloneOSX by Xcode. I suspect there is a nil pointer causing the crash. Identifying which will probably solve the problem..
I will also try to setup a Google Drive API later next week. I have been on winter vacation for about a week and heading back home later today..

**Comment by rsyncOSX** [comment]
I have juste released a new version of RsyncOSX. I will now see if I can reproduce the bug you have discovered (in a few days)...

**Comment by rsyncOSX** [comment]
I have created a Google Drive connection utilizing Google Drive APIs and an OAuth token .. I am not able to reproduce any crash/bugs and testfiles are successfully syncronized..

<img width="1027" alt="Skjermbilde 2020-02-29 kl  16 08 26" src="https://user-images.githubusercontent.com/22427340/75610060-4562e400-5b0e-11ea-99bd-019b163c49ad.png">
<img width="1204" alt="Skjermbilde 2020-02-29 kl  16 07 44" src="https://user-images.githubusercontent.com/22427340/75610064-485dd480-5b0e-11ea-87a5-417dfd7b4e6a.png">

**Comment by rsyncOSX** [comment]
I am working on next version
https://rsyncosx.github.io/RcloneChangelog

**Comment by cyberjew** [comment]
Ok cool. I’ll keep an eye out for it and hopefully it will resolve the
crash issue.

What version of MacOS are you using?

**Comment by rsyncOSX** [comment]
I am on macOS 10.15.3 - Catalina
I will make a release candidate for you to try out during the coming weekend..

**Comment by rsyncOSX** [comment]
Hi, just uploaded a rc of the new release.. The rc is NOT notarized, only signed.
Please just verify it dont crash and only do estimates in the restore tab..
And there is still work to do before release...
https://www.dropbox.com/sh/5pe9h2fh4md2n15/AABaR0sZk1JVvs82QXpzIYsTa?dl=0
shasum : 451b19fb098c5660372f3b625c3fe8f0e5435f2f

**Comment by rsyncOSX** [comment]
I synced my GitHub catalog, about 277 MB and 1740 files in 20 min to my google account setup by Google Drive API and Oauth.. I also, in restore, collected all files synced...
<img width="1204" alt="Skjermbilde 2020-03-06 kl  11 10 16" src="https://user-images.githubusercontent.com/22427340/76078429-f0f2b500-5fa2-11ea-9a5d-ae1b895124b6.png">
<img width="1204" alt="Skjermbilde 2020-03-06 kl  11 10 06" src="https://user-images.githubusercontent.com/22427340/76078435-f3eda580-5fa2-11ea-812d-e7196916d93f.png">
